### ISSUE TITLE
Pressing the `space` key prevents you from launching an attack.

### ISSUE THREAD

**Issue by kjxbyz** [RafaelBarbosatec/darkness_dungeon#10]
Pressing the `space` key prevents you from launching an attack.

**Comment by RafaelBarbosatec** [comment]
Hi @kjxbyz !
Thanks for reporting it.
In the line 59 of player. I need remove the .keyId
In the Bonfire 3.0 there return a LogicalKeyboardKey

**Comment by RafaelBarbosatec** [comment]
I will fix it

**Comment by kjxbyz** [comment]
It works for me. Thank you.
